<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<title>NoRoadBlockMtl</title>
<!--link href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" /-->
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="http://code.jquery.com/jquery-1.5.js"></script>
<script type="text/javascript">
  var directionDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;

//Set the path generated by Google as modifiable on the map by the user
var rendererOptions = {
  draggable: true
};

//Function called when loading the page
  function initialize() {
  	//Define the map
    directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);
    var myCentre = new google.maps.LatLng(45.50, -73.55);
    var myOptions = {
      zoom:9,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: myCentre
    }

	//Set the DIV to be used to display the Google Map
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    directionsDisplay.setMap(map);


//Listener to track the changes in the path
//Disabled for the moment, it seems to create an infinite loop somewhere...

    google.maps.event.addListener(directionsDisplay, 'directions_changed', function() {
    //calcRoute();
	processRoute(directionsDisplay.directions);
   }); 

}


function calcRoute() {

	//Get the start and end point from the form  	
	  var start = document.getElementById("start").value;
	  var end = document.getElementById("end").value;

	//Prepare and send request to Google
    var request = {
        origin:start, 
        destination:end,
        travelMode: google.maps.DirectionsTravelMode.DRIVING
    };

  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
  
  
  
   var mapBounds = map.getBounds();
   //alert (mapBounds);
	var northEast = mapBounds.getNorthEast();
	var southWest = mapBounds.getSouthWest();	
	var neLat = northEast.lat();
	var neLon = northEast.lng();
	var swLat = southWest.lat();
	var swLon = southWest.lng();
	var url = "http://96.21.124.183:8080/NoRoadBlockMtl/api/works.json?q=toto";
//	var query = "?nelat=" +  neLat + "&nelon=" + neLon + "&swlat=" + swLat + "&swlon=" + swLon;
//	alert(url + query);  
   
   $.getJSON(url,"",
  function(data) {


	for (i in data){
		var travaux = [];
		//alert(data[i]["name"]);
		
		for (j in data[i]["coordinates"]){
			var splited = data[i]["coordinates"][j].split(" ");
			var pointpassage = new google.maps.LatLng(splited[1], splited[0]);
			travaux.push(pointpassage);
//		alert(formated);
		}
		
		alert("Taille du array" + travaux.length);
		
	   var marker = new google.maps.Marker({
   	   position: travaux[0], 
      		map: map, 
 			});
  		
		if (travaux.length > 1){		
  			var zeLigne = new google.maps.Polyline({
    			path: travaux,
    			strokeColor: "#FF0000",
    			strokeOpacity: 0.5,
    			strokeWeight: 6
  			});

  			zeLigne.setMap(map);
		}
	}
  
  });

}
  
function processRoute (result) {

		//Retrieve and format the path. Target format is "long1 lat1, long2 lat2, ..."
		var fullString = "";
	  	var myRoute = result.routes[0].overview_path;

	  	for (var i = 0; i < myRoute.length; i++) {
			var exploded = (myRoute[i] + ",").split(",");
			fullString +=  exploded[1].replace(")", "").substring(1, 11) + " " + exploded[0].replace("(", "").substring(0, 10) + ",";


/*
			//Small code to print all the points of the path on the map.
			var marker = new google.maps.Marker({position: myRoute[i], map: map});

			google.maps.event.addListener(marker, 'click', function() {
			  infowindow.open(map,marker);
			});*/
        }


	  fullString = fullString.replace(")", "");
	  fullString = fullString.replace("(", "");
	  
	  //Set the value of an hidden form field to be sent to the server.
	  var postValue = document.getElementById('hiddenpath');
	  postValue.value = fullString.substring(0, fullString.length - 2);

}   

function postJson () {
	
		myObject = new Object();	
	
	  var postValue = document.getElementById('hiddenpath');
	  myObject.route = postValue.value;
	  myObject.name = document.getElementById('routename').value;		
	  var theData = JSON.stringify(myObject);
	alert(theData);
		$.post('http://96.21.124.183:8080/NoRoadBlockMtl/api/routes.json', { data: theData});
}

</script>
</head>
<body onload="initialize()">
<div>
<b>Start: </b> <input id="start" type="text" name="start" value="5233 av de gaspé, Montréal, qc"/>&nbsp;&nbsp;&nbsp;
<b>End: </b> <input id="end" type="text" name="end" value="510, sherbrooke west, montréal, qc"/>&nbsp;&nbsp;&nbsp;
<input type="button" value="Tracer trajet" onclick="calcRoute();"/>&nbsp;&nbsp;&nbsp;

<form action="postme.php" method="post">
<input type="text" name="hiddenpath" id="hiddenpath" value=""/>
<input type="text" name="distance" id="distance" value="distance" />
<input type="text" name="userid" id="userid" value="user id to be sent" />
<input type="text" name="routename" id="routename" value="Maison => Notman house" />
<input type="submit" value="Valider trajet"/>&nbsp;&nbsp;&nbsp;
<input type="button" value="Throw Json Post"  onclick="postJson()"/>
</form>

</div>
<div>&nbsp;</div>
<div style="width:100%; height:500px" id="map_canvas"></div>
</body>
</html>
